server:
  port: 10032
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 102400KB
      max-request-size: 102400KB
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://pradar.host.mysql.amdb:3306/amdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: shulie@2020
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

tro:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://pradar.host.mysql.tro:3306/trodb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: shulie@2020

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:generator/**/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

influx:
  openurl: http://pradar.host.influxdb:8086
  username: pradar
  password: pradar
  database: pradar

zookeeper:
  server: pradar.host.zk01:2181,pradar.host.zk02:2181,pradar.host.zk03:2181

datasource:
  # t_trace_all 数据源类型 支持mysql、clickhouse
  traceAll: clickhouse

config:
  clickhouse:
    enable: true
    url: jdbc:clickhouse://pradar.host.clickhouse01:8123,pradar.host.clickhouse02:8123/default
    userName: default
    password: rU4zGjA/
    enableRound: true
  adaptor:
    instance:
      open: false
  link:
    processUnknow: false
  e2e:
    delaySec: 120
  trace:
    limit: 500
  agentlog:
    reserveDays: 7
  tenantConfig:
    host: pradar.host.troweb
    port: 10008
    url: /takin-web/api/tenant/app/all
    defaultTenantAppKey: default
  entryRule:
    url: /takin-web/api/v1/api/pull
    queryThreads: 20

app:
  version: @project.version@
  build:
    time: @timestamp@