CREATE TABLE {table_name} {cluster_name}
(
    `appName` String,
    `entranceId` Nullable(String),
    `entranceNodeId` Nullable(String),
    `traceId` String,
    `level` Nullable(Int8),
    `parentIndex` Nullable(Int8),
    `index` Nullable(Int8),
    `rpcId` String,
    `rpcType` Int8,
    `logType` Nullable(Int8),
    `traceAppName` Nullable(String),
    `upAppName` Nullable(String),
    `startTime` Int64,
    `cost` Int32,
    `middlewareName` Nullable(String),
    `serviceName` Nullable(String),
    `methodName` Nullable(String),
    `remoteIp` Nullable(String),
    `port` Nullable(Int32),
    `resultCode` Nullable(String),
    `requestSize` Nullable(String),
    `responseSize` Nullable(String),
    `request` Nullable(String),
    `response` Nullable(String),
    `clusterTest` Nullable(String),
    `callbackMsg` Nullable(String),
    `samplingInterval` Nullable(String),
    `localId` Nullable(String),
    `attributes` Nullable(String),
    `localAttributes` Nullable(String),
    `async` Nullable(String),
    `version` Nullable(String),
    `hostIp` Nullable(String),
    `agentId` Nullable(String),
    `startDate` DateTime,
    `createDate` DateTime DEFAULT toDateTime(now()),
    `timeMin` Nullable(Int64) DEFAULT 0,
    `entranceServiceType` Nullable(String),
    `parsedServiceName` String,
    `parsedMethod` String,
    `parsedAppName` Nullable(String),
    `parsedMiddlewareName` Nullable(String),
    `parsedExtend` Nullable(String),
    `dateToMin` Int64,
    `taskId` String,
    `flag` Nullable(String),
    `flagMessage` Nullable(String),
    `receiveTime` Nullable(Int64),
    `processTime` Nullable(Int64),
    `saveCkTime` DateTime DEFAULT now(),
    `userAppKey` String,
    `envCode` String,
    `userId` String,
    `timeWindow` Nullable(DateTime),
    INDEX ix_traceid traceId TYPE set(0) GRANULARITY 5,
    INDEX ix_appName appName TYPE set(0) GRANULARITY 5,
    INDEX ix_parsedServiceName parsedServiceName TYPE set(0) GRANULARITY 5,
    INDEX ix_parsedMethod parsedMethod TYPE set(0) GRANULARITY 5
) ENGINE = ReplacingMergeTree
PRIMARY KEY (traceId, appName, parsedServiceName, parsedMethod, rpcType, rpcId)
ORDER BY (traceId, appName, parsedServiceName, parsedMethod, rpcType, rpcId)
TTL startDate + toIntervalDay(7)
SETTINGS index_granularity = 8192